// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/repositories.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/repositories.go -destination=internal/mocks/repository_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/itsLeonB/billsplittr/internal/entity"
	crud "github.com/itsLeonB/go-crud"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockGroupExpenseRepository is a mock of GroupExpenseRepository interface.
type MockGroupExpenseRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGroupExpenseRepositoryMockRecorder
	isgomock struct{}
}

// MockGroupExpenseRepositoryMockRecorder is the mock recorder for MockGroupExpenseRepository.
type MockGroupExpenseRepositoryMockRecorder struct {
	mock *MockGroupExpenseRepository
}

// NewMockGroupExpenseRepository creates a new mock instance.
func NewMockGroupExpenseRepository(ctrl *gomock.Controller) *MockGroupExpenseRepository {
	mock := &MockGroupExpenseRepository{ctrl: ctrl}
	mock.recorder = &MockGroupExpenseRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGroupExpenseRepository) EXPECT() *MockGroupExpenseRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockGroupExpenseRepository) Delete(ctx context.Context, model entity.GroupExpense) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, model)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockGroupExpenseRepositoryMockRecorder) Delete(ctx, model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockGroupExpenseRepository)(nil).Delete), ctx, model)
}

// DeleteMany mocks base method.
func (m *MockGroupExpenseRepository) DeleteMany(ctx context.Context, models []entity.GroupExpense) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMany", ctx, models)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMany indicates an expected call of DeleteMany.
func (mr *MockGroupExpenseRepositoryMockRecorder) DeleteMany(ctx, models any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMany", reflect.TypeOf((*MockGroupExpenseRepository)(nil).DeleteMany), ctx, models)
}

// FindAll mocks base method.
func (m *MockGroupExpenseRepository) FindAll(ctx context.Context, spec crud.Specification[entity.GroupExpense]) ([]entity.GroupExpense, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, spec)
	ret0, _ := ret[0].([]entity.GroupExpense)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockGroupExpenseRepositoryMockRecorder) FindAll(ctx, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockGroupExpenseRepository)(nil).FindAll), ctx, spec)
}

// FindFirst mocks base method.
func (m *MockGroupExpenseRepository) FindFirst(ctx context.Context, spec crud.Specification[entity.GroupExpense]) (entity.GroupExpense, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindFirst", ctx, spec)
	ret0, _ := ret[0].(entity.GroupExpense)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindFirst indicates an expected call of FindFirst.
func (mr *MockGroupExpenseRepositoryMockRecorder) FindFirst(ctx, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindFirst", reflect.TypeOf((*MockGroupExpenseRepository)(nil).FindFirst), ctx, spec)
}

// GetGormInstance mocks base method.
func (m *MockGroupExpenseRepository) GetGormInstance(ctx context.Context) (*gorm.DB, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGormInstance", ctx)
	ret0, _ := ret[0].(*gorm.DB)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGormInstance indicates an expected call of GetGormInstance.
func (mr *MockGroupExpenseRepositoryMockRecorder) GetGormInstance(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGormInstance", reflect.TypeOf((*MockGroupExpenseRepository)(nil).GetGormInstance), ctx)
}

// Insert mocks base method.
func (m *MockGroupExpenseRepository) Insert(ctx context.Context, model entity.GroupExpense) (entity.GroupExpense, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, model)
	ret0, _ := ret[0].(entity.GroupExpense)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockGroupExpenseRepositoryMockRecorder) Insert(ctx, model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockGroupExpenseRepository)(nil).Insert), ctx, model)
}

// InsertMany mocks base method.
func (m *MockGroupExpenseRepository) InsertMany(ctx context.Context, models []entity.GroupExpense) ([]entity.GroupExpense, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertMany", ctx, models)
	ret0, _ := ret[0].([]entity.GroupExpense)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertMany indicates an expected call of InsertMany.
func (mr *MockGroupExpenseRepositoryMockRecorder) InsertMany(ctx, models any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertMany", reflect.TypeOf((*MockGroupExpenseRepository)(nil).InsertMany), ctx, models)
}

// SaveMany mocks base method.
func (m *MockGroupExpenseRepository) SaveMany(ctx context.Context, models []entity.GroupExpense) ([]entity.GroupExpense, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMany", ctx, models)
	ret0, _ := ret[0].([]entity.GroupExpense)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveMany indicates an expected call of SaveMany.
func (mr *MockGroupExpenseRepositoryMockRecorder) SaveMany(ctx, models any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMany", reflect.TypeOf((*MockGroupExpenseRepository)(nil).SaveMany), ctx, models)
}

// SyncParticipants mocks base method.
func (m *MockGroupExpenseRepository) SyncParticipants(ctx context.Context, groupExpenseID uuid.UUID, participants []entity.ExpenseParticipant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncParticipants", ctx, groupExpenseID, participants)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncParticipants indicates an expected call of SyncParticipants.
func (mr *MockGroupExpenseRepositoryMockRecorder) SyncParticipants(ctx, groupExpenseID, participants any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncParticipants", reflect.TypeOf((*MockGroupExpenseRepository)(nil).SyncParticipants), ctx, groupExpenseID, participants)
}

// Update mocks base method.
func (m *MockGroupExpenseRepository) Update(ctx context.Context, model entity.GroupExpense) (entity.GroupExpense, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, model)
	ret0, _ := ret[0].(entity.GroupExpense)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockGroupExpenseRepositoryMockRecorder) Update(ctx, model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockGroupExpenseRepository)(nil).Update), ctx, model)
}

// MockExpenseItemRepository is a mock of ExpenseItemRepository interface.
type MockExpenseItemRepository struct {
	ctrl     *gomock.Controller
	recorder *MockExpenseItemRepositoryMockRecorder
	isgomock struct{}
}

// MockExpenseItemRepositoryMockRecorder is the mock recorder for MockExpenseItemRepository.
type MockExpenseItemRepositoryMockRecorder struct {
	mock *MockExpenseItemRepository
}

// NewMockExpenseItemRepository creates a new mock instance.
func NewMockExpenseItemRepository(ctrl *gomock.Controller) *MockExpenseItemRepository {
	mock := &MockExpenseItemRepository{ctrl: ctrl}
	mock.recorder = &MockExpenseItemRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExpenseItemRepository) EXPECT() *MockExpenseItemRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockExpenseItemRepository) Delete(ctx context.Context, model entity.ExpenseItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, model)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockExpenseItemRepositoryMockRecorder) Delete(ctx, model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockExpenseItemRepository)(nil).Delete), ctx, model)
}

// DeleteMany mocks base method.
func (m *MockExpenseItemRepository) DeleteMany(ctx context.Context, models []entity.ExpenseItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMany", ctx, models)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMany indicates an expected call of DeleteMany.
func (mr *MockExpenseItemRepositoryMockRecorder) DeleteMany(ctx, models any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMany", reflect.TypeOf((*MockExpenseItemRepository)(nil).DeleteMany), ctx, models)
}

// FindAll mocks base method.
func (m *MockExpenseItemRepository) FindAll(ctx context.Context, spec crud.Specification[entity.ExpenseItem]) ([]entity.ExpenseItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, spec)
	ret0, _ := ret[0].([]entity.ExpenseItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockExpenseItemRepositoryMockRecorder) FindAll(ctx, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockExpenseItemRepository)(nil).FindAll), ctx, spec)
}

// FindFirst mocks base method.
func (m *MockExpenseItemRepository) FindFirst(ctx context.Context, spec crud.Specification[entity.ExpenseItem]) (entity.ExpenseItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindFirst", ctx, spec)
	ret0, _ := ret[0].(entity.ExpenseItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindFirst indicates an expected call of FindFirst.
func (mr *MockExpenseItemRepositoryMockRecorder) FindFirst(ctx, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindFirst", reflect.TypeOf((*MockExpenseItemRepository)(nil).FindFirst), ctx, spec)
}

// GetGormInstance mocks base method.
func (m *MockExpenseItemRepository) GetGormInstance(ctx context.Context) (*gorm.DB, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGormInstance", ctx)
	ret0, _ := ret[0].(*gorm.DB)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGormInstance indicates an expected call of GetGormInstance.
func (mr *MockExpenseItemRepositoryMockRecorder) GetGormInstance(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGormInstance", reflect.TypeOf((*MockExpenseItemRepository)(nil).GetGormInstance), ctx)
}

// Insert mocks base method.
func (m *MockExpenseItemRepository) Insert(ctx context.Context, model entity.ExpenseItem) (entity.ExpenseItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, model)
	ret0, _ := ret[0].(entity.ExpenseItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockExpenseItemRepositoryMockRecorder) Insert(ctx, model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockExpenseItemRepository)(nil).Insert), ctx, model)
}

// InsertMany mocks base method.
func (m *MockExpenseItemRepository) InsertMany(ctx context.Context, models []entity.ExpenseItem) ([]entity.ExpenseItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertMany", ctx, models)
	ret0, _ := ret[0].([]entity.ExpenseItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertMany indicates an expected call of InsertMany.
func (mr *MockExpenseItemRepositoryMockRecorder) InsertMany(ctx, models any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertMany", reflect.TypeOf((*MockExpenseItemRepository)(nil).InsertMany), ctx, models)
}

// SaveMany mocks base method.
func (m *MockExpenseItemRepository) SaveMany(ctx context.Context, models []entity.ExpenseItem) ([]entity.ExpenseItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMany", ctx, models)
	ret0, _ := ret[0].([]entity.ExpenseItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveMany indicates an expected call of SaveMany.
func (mr *MockExpenseItemRepositoryMockRecorder) SaveMany(ctx, models any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMany", reflect.TypeOf((*MockExpenseItemRepository)(nil).SaveMany), ctx, models)
}

// SyncParticipants mocks base method.
func (m *MockExpenseItemRepository) SyncParticipants(ctx context.Context, expenseItemID uuid.UUID, participants []entity.ItemParticipant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncParticipants", ctx, expenseItemID, participants)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncParticipants indicates an expected call of SyncParticipants.
func (mr *MockExpenseItemRepositoryMockRecorder) SyncParticipants(ctx, expenseItemID, participants any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncParticipants", reflect.TypeOf((*MockExpenseItemRepository)(nil).SyncParticipants), ctx, expenseItemID, participants)
}

// Update mocks base method.
func (m *MockExpenseItemRepository) Update(ctx context.Context, model entity.ExpenseItem) (entity.ExpenseItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, model)
	ret0, _ := ret[0].(entity.ExpenseItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockExpenseItemRepositoryMockRecorder) Update(ctx, model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockExpenseItemRepository)(nil).Update), ctx, model)
}

// MockExpenseParticipantRepository is a mock of ExpenseParticipantRepository interface.
type MockExpenseParticipantRepository struct {
	ctrl     *gomock.Controller
	recorder *MockExpenseParticipantRepositoryMockRecorder
	isgomock struct{}
}

// MockExpenseParticipantRepositoryMockRecorder is the mock recorder for MockExpenseParticipantRepository.
type MockExpenseParticipantRepositoryMockRecorder struct {
	mock *MockExpenseParticipantRepository
}

// NewMockExpenseParticipantRepository creates a new mock instance.
func NewMockExpenseParticipantRepository(ctrl *gomock.Controller) *MockExpenseParticipantRepository {
	mock := &MockExpenseParticipantRepository{ctrl: ctrl}
	mock.recorder = &MockExpenseParticipantRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExpenseParticipantRepository) EXPECT() *MockExpenseParticipantRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockExpenseParticipantRepository) Delete(ctx context.Context, model entity.ExpenseParticipant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, model)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockExpenseParticipantRepositoryMockRecorder) Delete(ctx, model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockExpenseParticipantRepository)(nil).Delete), ctx, model)
}

// DeleteMany mocks base method.
func (m *MockExpenseParticipantRepository) DeleteMany(ctx context.Context, models []entity.ExpenseParticipant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMany", ctx, models)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMany indicates an expected call of DeleteMany.
func (mr *MockExpenseParticipantRepositoryMockRecorder) DeleteMany(ctx, models any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMany", reflect.TypeOf((*MockExpenseParticipantRepository)(nil).DeleteMany), ctx, models)
}

// FindAll mocks base method.
func (m *MockExpenseParticipantRepository) FindAll(ctx context.Context, spec crud.Specification[entity.ExpenseParticipant]) ([]entity.ExpenseParticipant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, spec)
	ret0, _ := ret[0].([]entity.ExpenseParticipant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockExpenseParticipantRepositoryMockRecorder) FindAll(ctx, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockExpenseParticipantRepository)(nil).FindAll), ctx, spec)
}

// FindFirst mocks base method.
func (m *MockExpenseParticipantRepository) FindFirst(ctx context.Context, spec crud.Specification[entity.ExpenseParticipant]) (entity.ExpenseParticipant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindFirst", ctx, spec)
	ret0, _ := ret[0].(entity.ExpenseParticipant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindFirst indicates an expected call of FindFirst.
func (mr *MockExpenseParticipantRepositoryMockRecorder) FindFirst(ctx, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindFirst", reflect.TypeOf((*MockExpenseParticipantRepository)(nil).FindFirst), ctx, spec)
}

// GetGormInstance mocks base method.
func (m *MockExpenseParticipantRepository) GetGormInstance(ctx context.Context) (*gorm.DB, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGormInstance", ctx)
	ret0, _ := ret[0].(*gorm.DB)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGormInstance indicates an expected call of GetGormInstance.
func (mr *MockExpenseParticipantRepositoryMockRecorder) GetGormInstance(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGormInstance", reflect.TypeOf((*MockExpenseParticipantRepository)(nil).GetGormInstance), ctx)
}

// Insert mocks base method.
func (m *MockExpenseParticipantRepository) Insert(ctx context.Context, model entity.ExpenseParticipant) (entity.ExpenseParticipant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, model)
	ret0, _ := ret[0].(entity.ExpenseParticipant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockExpenseParticipantRepositoryMockRecorder) Insert(ctx, model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockExpenseParticipantRepository)(nil).Insert), ctx, model)
}

// InsertMany mocks base method.
func (m *MockExpenseParticipantRepository) InsertMany(ctx context.Context, models []entity.ExpenseParticipant) ([]entity.ExpenseParticipant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertMany", ctx, models)
	ret0, _ := ret[0].([]entity.ExpenseParticipant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertMany indicates an expected call of InsertMany.
func (mr *MockExpenseParticipantRepositoryMockRecorder) InsertMany(ctx, models any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertMany", reflect.TypeOf((*MockExpenseParticipantRepository)(nil).InsertMany), ctx, models)
}

// SaveMany mocks base method.
func (m *MockExpenseParticipantRepository) SaveMany(ctx context.Context, models []entity.ExpenseParticipant) ([]entity.ExpenseParticipant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMany", ctx, models)
	ret0, _ := ret[0].([]entity.ExpenseParticipant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveMany indicates an expected call of SaveMany.
func (mr *MockExpenseParticipantRepositoryMockRecorder) SaveMany(ctx, models any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMany", reflect.TypeOf((*MockExpenseParticipantRepository)(nil).SaveMany), ctx, models)
}

// Update mocks base method.
func (m *MockExpenseParticipantRepository) Update(ctx context.Context, model entity.ExpenseParticipant) (entity.ExpenseParticipant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, model)
	ret0, _ := ret[0].(entity.ExpenseParticipant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockExpenseParticipantRepositoryMockRecorder) Update(ctx, model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockExpenseParticipantRepository)(nil).Update), ctx, model)
}

// MockOtherFeeRepository is a mock of OtherFeeRepository interface.
type MockOtherFeeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOtherFeeRepositoryMockRecorder
	isgomock struct{}
}

// MockOtherFeeRepositoryMockRecorder is the mock recorder for MockOtherFeeRepository.
type MockOtherFeeRepositoryMockRecorder struct {
	mock *MockOtherFeeRepository
}

// NewMockOtherFeeRepository creates a new mock instance.
func NewMockOtherFeeRepository(ctrl *gomock.Controller) *MockOtherFeeRepository {
	mock := &MockOtherFeeRepository{ctrl: ctrl}
	mock.recorder = &MockOtherFeeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOtherFeeRepository) EXPECT() *MockOtherFeeRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockOtherFeeRepository) Delete(ctx context.Context, model entity.OtherFee) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, model)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockOtherFeeRepositoryMockRecorder) Delete(ctx, model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockOtherFeeRepository)(nil).Delete), ctx, model)
}

// DeleteMany mocks base method.
func (m *MockOtherFeeRepository) DeleteMany(ctx context.Context, models []entity.OtherFee) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMany", ctx, models)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMany indicates an expected call of DeleteMany.
func (mr *MockOtherFeeRepositoryMockRecorder) DeleteMany(ctx, models any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMany", reflect.TypeOf((*MockOtherFeeRepository)(nil).DeleteMany), ctx, models)
}

// FindAll mocks base method.
func (m *MockOtherFeeRepository) FindAll(ctx context.Context, spec crud.Specification[entity.OtherFee]) ([]entity.OtherFee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, spec)
	ret0, _ := ret[0].([]entity.OtherFee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockOtherFeeRepositoryMockRecorder) FindAll(ctx, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockOtherFeeRepository)(nil).FindAll), ctx, spec)
}

// FindFirst mocks base method.
func (m *MockOtherFeeRepository) FindFirst(ctx context.Context, spec crud.Specification[entity.OtherFee]) (entity.OtherFee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindFirst", ctx, spec)
	ret0, _ := ret[0].(entity.OtherFee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindFirst indicates an expected call of FindFirst.
func (mr *MockOtherFeeRepositoryMockRecorder) FindFirst(ctx, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindFirst", reflect.TypeOf((*MockOtherFeeRepository)(nil).FindFirst), ctx, spec)
}

// GetGormInstance mocks base method.
func (m *MockOtherFeeRepository) GetGormInstance(ctx context.Context) (*gorm.DB, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGormInstance", ctx)
	ret0, _ := ret[0].(*gorm.DB)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGormInstance indicates an expected call of GetGormInstance.
func (mr *MockOtherFeeRepositoryMockRecorder) GetGormInstance(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGormInstance", reflect.TypeOf((*MockOtherFeeRepository)(nil).GetGormInstance), ctx)
}

// Insert mocks base method.
func (m *MockOtherFeeRepository) Insert(ctx context.Context, model entity.OtherFee) (entity.OtherFee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, model)
	ret0, _ := ret[0].(entity.OtherFee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockOtherFeeRepositoryMockRecorder) Insert(ctx, model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockOtherFeeRepository)(nil).Insert), ctx, model)
}

// InsertMany mocks base method.
func (m *MockOtherFeeRepository) InsertMany(ctx context.Context, models []entity.OtherFee) ([]entity.OtherFee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertMany", ctx, models)
	ret0, _ := ret[0].([]entity.OtherFee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertMany indicates an expected call of InsertMany.
func (mr *MockOtherFeeRepositoryMockRecorder) InsertMany(ctx, models any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertMany", reflect.TypeOf((*MockOtherFeeRepository)(nil).InsertMany), ctx, models)
}

// SaveMany mocks base method.
func (m *MockOtherFeeRepository) SaveMany(ctx context.Context, models []entity.OtherFee) ([]entity.OtherFee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMany", ctx, models)
	ret0, _ := ret[0].([]entity.OtherFee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveMany indicates an expected call of SaveMany.
func (mr *MockOtherFeeRepositoryMockRecorder) SaveMany(ctx, models any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMany", reflect.TypeOf((*MockOtherFeeRepository)(nil).SaveMany), ctx, models)
}

// SyncParticipants mocks base method.
func (m *MockOtherFeeRepository) SyncParticipants(ctx context.Context, feeID uuid.UUID, participants []entity.FeeParticipant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncParticipants", ctx, feeID, participants)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncParticipants indicates an expected call of SyncParticipants.
func (mr *MockOtherFeeRepositoryMockRecorder) SyncParticipants(ctx, feeID, participants any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncParticipants", reflect.TypeOf((*MockOtherFeeRepository)(nil).SyncParticipants), ctx, feeID, participants)
}

// Update mocks base method.
func (m *MockOtherFeeRepository) Update(ctx context.Context, model entity.OtherFee) (entity.OtherFee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, model)
	ret0, _ := ret[0].(entity.OtherFee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockOtherFeeRepositoryMockRecorder) Update(ctx, model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockOtherFeeRepository)(nil).Update), ctx, model)
}

// MockExpenseBillRepository is a mock of ExpenseBillRepository interface.
type MockExpenseBillRepository struct {
	ctrl     *gomock.Controller
	recorder *MockExpenseBillRepositoryMockRecorder
	isgomock struct{}
}

// MockExpenseBillRepositoryMockRecorder is the mock recorder for MockExpenseBillRepository.
type MockExpenseBillRepositoryMockRecorder struct {
	mock *MockExpenseBillRepository
}

// NewMockExpenseBillRepository creates a new mock instance.
func NewMockExpenseBillRepository(ctrl *gomock.Controller) *MockExpenseBillRepository {
	mock := &MockExpenseBillRepository{ctrl: ctrl}
	mock.recorder = &MockExpenseBillRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExpenseBillRepository) EXPECT() *MockExpenseBillRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockExpenseBillRepository) Delete(ctx context.Context, model entity.ExpenseBill) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, model)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockExpenseBillRepositoryMockRecorder) Delete(ctx, model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockExpenseBillRepository)(nil).Delete), ctx, model)
}

// DeleteMany mocks base method.
func (m *MockExpenseBillRepository) DeleteMany(ctx context.Context, models []entity.ExpenseBill) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMany", ctx, models)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMany indicates an expected call of DeleteMany.
func (mr *MockExpenseBillRepositoryMockRecorder) DeleteMany(ctx, models any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMany", reflect.TypeOf((*MockExpenseBillRepository)(nil).DeleteMany), ctx, models)
}

// FindAll mocks base method.
func (m *MockExpenseBillRepository) FindAll(ctx context.Context, spec crud.Specification[entity.ExpenseBill]) ([]entity.ExpenseBill, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, spec)
	ret0, _ := ret[0].([]entity.ExpenseBill)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockExpenseBillRepositoryMockRecorder) FindAll(ctx, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockExpenseBillRepository)(nil).FindAll), ctx, spec)
}

// FindFirst mocks base method.
func (m *MockExpenseBillRepository) FindFirst(ctx context.Context, spec crud.Specification[entity.ExpenseBill]) (entity.ExpenseBill, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindFirst", ctx, spec)
	ret0, _ := ret[0].(entity.ExpenseBill)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindFirst indicates an expected call of FindFirst.
func (mr *MockExpenseBillRepositoryMockRecorder) FindFirst(ctx, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindFirst", reflect.TypeOf((*MockExpenseBillRepository)(nil).FindFirst), ctx, spec)
}

// GetGormInstance mocks base method.
func (m *MockExpenseBillRepository) GetGormInstance(ctx context.Context) (*gorm.DB, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGormInstance", ctx)
	ret0, _ := ret[0].(*gorm.DB)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGormInstance indicates an expected call of GetGormInstance.
func (mr *MockExpenseBillRepositoryMockRecorder) GetGormInstance(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGormInstance", reflect.TypeOf((*MockExpenseBillRepository)(nil).GetGormInstance), ctx)
}

// Insert mocks base method.
func (m *MockExpenseBillRepository) Insert(ctx context.Context, model entity.ExpenseBill) (entity.ExpenseBill, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, model)
	ret0, _ := ret[0].(entity.ExpenseBill)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockExpenseBillRepositoryMockRecorder) Insert(ctx, model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockExpenseBillRepository)(nil).Insert), ctx, model)
}

// InsertMany mocks base method.
func (m *MockExpenseBillRepository) InsertMany(ctx context.Context, models []entity.ExpenseBill) ([]entity.ExpenseBill, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertMany", ctx, models)
	ret0, _ := ret[0].([]entity.ExpenseBill)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertMany indicates an expected call of InsertMany.
func (mr *MockExpenseBillRepositoryMockRecorder) InsertMany(ctx, models any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertMany", reflect.TypeOf((*MockExpenseBillRepository)(nil).InsertMany), ctx, models)
}

// SaveMany mocks base method.
func (m *MockExpenseBillRepository) SaveMany(ctx context.Context, models []entity.ExpenseBill) ([]entity.ExpenseBill, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMany", ctx, models)
	ret0, _ := ret[0].([]entity.ExpenseBill)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveMany indicates an expected call of SaveMany.
func (mr *MockExpenseBillRepositoryMockRecorder) SaveMany(ctx, models any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMany", reflect.TypeOf((*MockExpenseBillRepository)(nil).SaveMany), ctx, models)
}

// Update mocks base method.
func (m *MockExpenseBillRepository) Update(ctx context.Context, model entity.ExpenseBill) (entity.ExpenseBill, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, model)
	ret0, _ := ret[0].(entity.ExpenseBill)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockExpenseBillRepositoryMockRecorder) Update(ctx, model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockExpenseBillRepository)(nil).Update), ctx, model)
}
